### PR TITLE
Python version selection support

### PR DESCRIPTION
**Pull request by Loghijiaha**
## Checklist

- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [x] Unit tests pass locally with my changes
- [ ] I have added documentation as necessary
- [ ] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [x] I have interactively tested my changes

## Types of changes

- [ ] Infrastructure change (non-breaking change which updates dependencies or improves infrastructure)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

version_sprt

### CODE REVIEW

**Comment by imoutsatsos** [comment]
I think that allowing execution of conda commands, rather than selection of a python version, would be more flexible and aligned with how we typically select an environment with the appropriate modules for the task at hand. This could be implemented as a text area to provide the commands.

**Comment by Loghijiaha** [comment]
I agree with this @bruno. And if we drop this feature, the user should be aware of `which python` they are using. As @imoutsatsos said, Would it be possible if we activate an environment through a Jenkins instance? @kinow ?

**Comment by kinow** [comment]
> I agree with this @bruno. And if we drop this feature, the user should be aware of `which python` they are using. As @imoutsatsos said, Would it be possible if we activate an environment through a Jenkins instance? @kinow ?

I think so @Loghijiaha . Though we need to take care to execute it in the same terminal session as the notebook execution.

Not sure if it would work if we executed a preload script like `conda activate my-env-1`, and then later continued with the `Callable` running the pipeline. I believe it needs to be activated in the agent, and the agent must execute the notebook using that virtual environment.

Might need some thinking on how to implement, and some time for testing (I can help with the latter, and we can research other plug-ins if it's hard to find out how to implement it.)

**Comment by Loghijiaha** [comment]
Closing this as not needed to discuss more.

**Pull request closed without merging**
